apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quarkuscoffeeshop-majestic-monolith-image
  labels:
    app: quarkuscoffeeshop-majestic-monolith
  namespace: quarkuscoffeeshop-cicd
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-cicd/quarkuscoffeeshop-majestic-monolith
