kind: Service
apiVersion: v1
metadata:
  name: quarkuscoffeeshop-inventory
  namespace: quarkuscoffeeshop-demo
  labels:
    app: quarkuscoffeeshop-inventory
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: quarkuscoffeeshop-inventory
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: quarkuscoffeeshop-inventory
  namespace: quarkuscoffeeshop-demo
  labels:
    app: quarkuscoffeeshop-inventory
    app.kubernetes.io/name: quarkus
    app.kubernetes.io/part-of: quarkuscoffeeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkuscoffeeshop-inventory
  template:
    metadata:
      name: quarkuscoffeeshop-inventory-deployment
      labels:
        app: quarkuscoffeeshop-inventory
        app.kubernetes.io/component: quarkuscoffeeshop-inventory
        app.kubernetes.io/instance: quarkuscoffeeshop-inventory
        app.kubernetes.io/part-of: quarkuscoffeeshop
        app.openshift.io/runtime-namespace: quarkuscoffeeshop-demo
        quarkuscoffeeshop: ''
    spec:
      containers:
        - name: quarkuscoffeeshop-inventory
          image: 'image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-cicd/quarkuscoffeeshop-inventory:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: 'cafe-cluster-kafka-bootstrap:9092'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600