apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-push-quarkuscoffeeshop-inventory
  labels:
    app: quarkuscoffeeshop-inventory
spec:
  params:
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
    - default: quay.io/quarkuscoffeeshop/quarkuscoffeeshop-inventory
      name: quay-io-repository
      type: string
    - default: latest
      name: quay-io-image-tag-name
      type: string
    - default: webhook-secret
      description: webhook secret name
      name: webhook-secret
      type: string
  resources:
    - name: app-git
      type: git
    - name: image
      type: image
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/quarkuscoffeeshop/quarkuscoffeeshop-inventory'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven-run
      params:
        - name: CONTEXT_DIR
          value: .
        - name: GOALS
          value:
            - '-DskipTests'
            - clean
            - package
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
    - name: build-java-app-image
      params:
        - name: CONTEXT
          value: .
        - name: DOCKERFILE
          value: src/main/docker/Dockerfile.jvm
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-cicd/quarkuscoffeeshop-inventory:$(params.IMAGE_TAG)
        - name: TLSVERIFY
          value: 'false'
      runAfter:
        - maven-run
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: tag-test-image
      params:
        - name: SCRIPT
          value: |
            oc tag quarkuscoffeeshop-inventory:$(params.IMAGE_TAG) quarkuscoffeeshop-inventory:latest
      runAfter:
        - build-java-app-image
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: push-to-test-env
      params:
        - name: SCRIPT
          value: |
            oc patch deployment/quarkuscoffeeshop-inventory  --patch='{"spec":{"template":{"spec":{"containers":[{"name":"quarkuscoffeeshop-inventory","image":"image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-cicd/quarkuscoffeeshop-inventory:'$(params.IMAGE_TAG)'"}]}}}}' -n quarkuscoffeeshop-demo
      runAfter:
        - tag-test-image
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: push-quarkuscoffeeshop-inventory-image-to-quay
      params:
        - name: quay-io-repository
          value: $(params.quay-io-repository)
        - name: quay-io-image-tag-name
          value: $(params.quay-io-image-tag-name)
      resources:
        inputs:
          - name: image
            resource: image
      runAfter:
        - push-to-test-env
      taskRef:
        kind: Task
        name: push-quarkuscoffeeshop-inventory-image-to-quay
  workspaces:
    - name: shared-workspace
    - name: maven-settings
