apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-push-quarkuscoffeeshop-homeoffice-ui
  labels:
    app: quarkuscoffeeshop-homeoffice-ui
spec:
  params:
    - default: takinosh
      name: quay-io-account
      type: string
    - default: >-
        http://homeoffice-backend-quarkuscoffeeshop-homeoffice.apps.shop.quarkuscoffeeshop.io/graphql
      description: The home office backend endpoint
      name: REACT_APP_GRAPHQL_ENDPOINT
      type: string
    - default: quay.io/quarkuscoffeeshop/quarkuscoffeeshop-homeoffice-ui
      name: quay-io-repository
      type: string
    - default: latest
      name: quay-io-image-tag-name
      type: string
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
    - default: >-
        --patch={"spec":{"template":{"spec":{"containers":[{"name":"quarkuscoffeeshop-homeoffice-ui","image":"image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-cicd/quarkuscoffeeshop-homeoffice-ui:$(params.IMAGE_TAG)"}]}}}}
      description: patch image
      name: PATCH_IMAGE
      type: string
    - default: webhook-secret
      description: Webhook secert name
      name: webhook-secret
      type: string
  resources:
    - name: app-git
      type: git
    - name: image
      type: image
  tasks:
    - name: build
      params:
        - name: TLSVERIFY
          value: 'false'
        - name: IMAGE_TAG
          value: $(params.IMAGE_TAG)
        - name: REACT_APP_GRAPHQL_ENDPOINT
          value: $(params.REACT_APP_GRAPHQL_ENDPOINT)
      resources:
        inputs:
          - name: source
            resource: app-git
        outputs:
          - name: image
            resource: image
      taskRef:
        kind: Task
        name: s2i-nodejs
    - name: tag-test-image
      params:
        - name: ARGS
          value:
            - tag
            - 'quarkuscoffeeshop-homeoffice-ui:$(params.IMAGE_TAG)'
            - 'quarkuscoffeeshop-homeoffice-ui:latest'
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: push-to-test-env
      params:
        - name: ARGS
          value:
            - patch
            - deployment/quarkuscoffeeshop-homeoffice-ui
            - $(params.PATCH_IMAGE)
            - '-n'
            - quarkuscoffeeshop-homeoffice
      runAfter:
        - tag-test-image
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: push-image-to-quay
      params:
        - name: quay-io-repository
          value: $(params.quay-io-repository)
        - name: quay-io-image-tag-name
          value: $(params.quay-io-image-tag-name)
      resources:
        inputs:
          - name: image
            resource: image
      runAfter:
        - push-to-test-env
      taskRef:
        kind: Task
        name: push-image-to-quay
    - name: send-to-webhook-slack
      params:
        - name: webhook-secret
          value: $(params.webhook-secret)
        - name: message
          value: >-
            Pipeline build pushed succesfully to 
            $(params.quay-io-repository):$(params.quay-io-image-tag-name)
      runAfter:
        - push-image-to-quay
      taskRef:
        kind: Task
        name: send-to-webhook-slack
